### ISSUE TITLE
Send email to Crystal, Colorado contact

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/project-tracking#14]

**Comment by RDmitchell** [comment]
@isalanglois  -- Email about what ?

**Comment by isalanglois** [comment]
Just a follow-up. On the call today with DOE, they mentioned needing to follow-up on if they need any more information about SEED and communicating some of the recent updates to SEED

**Comment by RDmitchell** [comment]
@nllong -- you are going to do that followup?

**Comment by nllong** [comment]
i just sent one. cc'd you all.
