### ISSUE TITLE
[1/27/2023]: Patch Release

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/project-tracking#15]
PR's Included:
-Fixed issue with overlapping meter readings with new ESPM format ([#3745](https://github.com/SEED-platform/seed/pull/3745))
-Show portfolio manager errors ([#3735](https://github.com/SEED-platform/seed/pull/3735))
-Update derived column migration to prevent conflicting column names and prevent duplicate column names ([#3728](https://github.com/SEED-platform/seed/pull/3728))
-Allow users to hide property insight dataset ([#3726](https://github.com/SEED-platform/seed/pull/3726))
-Fix bug where compliance calculations were not being cast the right data type ([#3789](https://github.com/orgs/SEED-platform/projects/4/views/1?pane=issue&itemId=18293016))

Ticket's to try and include: 

[#3759](https://github.com/SEED-platform/seed/issues/3759)

**Comment by isalanglois** [comment]
@RDmitchell
 Wanted to flag this for you

**Comment by RDmitchell** [comment]
The PR's above aren't linked to the actual PRs, which should be possible. 

Also, it would be good to see what issues are addressed with this patch.

**Comment by isalanglois** [comment]
@RDmitchell I am not sure why I couldn't link them like I usually do, but I added the title of the PR as well in description

**Comment by nllong** [comment]
finished. No testing needed for the issue, but please test the items in the `test` column of the project board.
