### ISSUE TITLE
[2/28/23] Develop WIP Dashboard Technical Specification

### ISSUE THREAD

**Issue by nllong** [SEED-platform/project-tracking#5]
Assess and document highest value needs for graphical capabilities in the form of a functional requirements document.	

Functional requirements suggest scope is cost reasonable and technically feasible

Doc:
https://docs.google.com/document/d/1KtSXyDgOA6o0xbxPvcKcOUGwaxMBGRZtROsuL0bFa1Q/edit

**Comment by isalanglois** [comment]
Tickets that might relate: 
-Property Insights graph: Labels for X-axis with lots of text based data points doesn’t display well ([#3807](https://github.com/orgs/SEED-platform/projects/4/views/1?filterQuery=property+insights&pane=issue&itemId=19098640))
-Insights: Property Insights screen needs UI refinement #3804 ([#3804](https://github.com/orgs/SEED-platform/projects/4/views/1?filterQuery=3804&pane=issue&itemId=19092987))

**Comment by isalanglois** [comment]
@RDmitchell We are working on a planning document in response to the listening sessions for the WIP work right now, and some of the tickets you made may be addressed in the specification document. 

We will be presenting this to the whole team at one of our upcoming iteration meetings. Feel free to review the spec document linked ahead of time, if you'd like. We went over some of these updates with Ammon today

**Comment by RDmitchell** [comment]
@isalanglois -- where is the spec doc?

**Comment by isalanglois** [comment]
@RDmitchell  In the first comment/description on this ticket (Nicholas'). It's not finalized yet, but these are the ideas so far

**Comment by RDmitchell** [comment]
got it, thx !

**Comment by RDmitchell** [comment]
@isalanglois -- is it possible to make the images larger? It's really hard to read them. I know basically what they are, but it would still be good if they were legible, if possible. thx
