### ISSUE TITLE
[8/22/22] Investigate why DOE reports page is not running the reports

### ISSUE THREAD

**Issue by isalanglois** [SEED-platform/project-tracking#6]

**Comment by isalanglois** [comment]
@nllong  Do you know if this issue is resolved? It was an action item from out DOE-SEED check-in a few weeks ago. We can bring it up in email with Sydney/Jeff when we ask about AOP?

**Comment by isalanglois** [comment]
9/19: Sydney is going to check and let us know if this is still persisting

**Comment by nllong** [comment]
closing. reopen if this continues to be an issue.
